name: Feature request
description: Suggest a feature idea for Curve Number Generator plugin.
labels:
  - 'enhancement'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request correctly.

  - type: checkboxes
    id: Curve Number Generator plugin-version
    attributes:
      label: Latest Curve Number Generator plugin version
      options:
        - label: I am running the latest Curve Number Generator plugin version

  - type: checkboxes
    id: similar-issues
    attributes:
      label: Similar requests do not exist
      options:
        - label: I have searched existing issues to make sure a similar request does not exist

  - type: textarea
    id: what
    attributes:
      label: Feature description
      description: A clear and concise description of what you want to happen. Ex. Curve Number Generator plugin would rock even more if [...]
    validations:
      required: true

  - type: textarea
    id: Additional
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.